config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "measures#index"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :measures
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/measure.rb
class Measure < ApplicationRecord
    scope :filter_by_measure_type, -> (measure_type) { where("measure_type like ?", "#{measure_type}%")}

    def self.ransackable_attributes(auth_object = nil)
        ["brand", 
        "created_at", 
        "date", 
        "establishment_address", 
        "establishment_city", 
        "establishment_id", 
        "establishment_latitude", 
        "establishment_longitude", 
        "establishment_name", 
        "establishment_postcode", 
        "id", 
        "measure_float", 
        "measure_type", 
        "room_name", 
        "serial_number", 
        "updated_at"]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/measures_controller.rb
class MeasuresController < ApplicationController
    def index
        @query = Measure.ransack(params[:q])
        @measures = @query.result(distinct: true)
        @measures_co2 = @measures.filter_by_measure_type("CO2")
        @measures_tmp = @measures.filter_by_measure_type("TMP")
        @measures_voct = @measures.filter_by_measure_type("VOCT")
        @measures_hum = @measures.filter_by_measure_type("HUM")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/measure_type_helper.rb
module MeasureTypeHelper
    def title(measure_type)
        a = []
        a.push(measure_type)
        a[0]
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppPando2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto">
      <%= yield %>
    </main>
  </body>
</html>

app/views/measures/_chart.html.erb
<% obj.each_with_index do |type, i| %>
  <%= title(type.measure_type) %>
  <% break if i == 0 %>
<% end %>

<% if obj.any? %>
  <%= line_chart obj.group(:room_name).group_by_hour(:date).sum(:measure_float),colors: ["#FF6663", "#DEB841","#000F08"] %>
<% end %>

app/views/measures/index.html.erb
<div class="flex flex-col m-8 space-y-5">
    <div class="flex justify-around">
        <div><%= image_tag "svg/logo.svg"%></div>
        <div>
            <%= search_form_for @query do |f| %>
                <%= f.select :room_name_cont, Measure.pluck(:room_name).uniq, prompt: "- Salles -" %>
                <%= f.select :measure_type_cont, Measure.pluck(:measure_type).uniq, prompt: "- Paramètres -" %>
                <%= f.submit "Ajouter Filtre", class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full" %>
                <%= link_to "Suprimer Filtre", measures_path, class:"bg-red-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full" %>
            <% end %>
        </div>
    </div>
    <div>
        <%= render "chart", obj: @measures_co2 %>
    </div>
    <div>
        <%= render "chart", obj: @measures_voct %>
    </div>
    <div>
        <%= render "chart", obj: @measures_hum %>
    </div>
    <div>
        <%= render "chart", obj: @measures_tmp %>
    </div>
</div>